export const ScheduleData = [
  {
    id: "1",
    scheduleId: "SHD0001",
    scheduleType: "Daily Fixed",
    startDate: "09/05/2025",
    endDate: "09/07/2025",
    hours: "10.00",
    rate: "$0.00",
    status: "active",
    weeklySchedule: [
      { day: "Monday", timeIn: "-:-", timeOut: "-:-" },
      { day: "TuesDay", timeIn: "-:-", timeOut: "-:-" },
      { day: "Wednesday", timeIn: "08:00", timeOut: "18:00" },
      { day: "Thursday", timeIn: "08:00", timeOut: "18:00" },
      { day: "Friday", timeIn: "-:-", timeOut: "-:-" },
      { day: "Saturday", timeIn: "-:-", timeOut: "-:-" },
    ],
  },

  {
    id: "2",
    scheduleId: "SHD0002",
    scheduleType: "Daily Fixed",
    startDate: "09/05/2025",
    endDate: "09/07/2025",
    hours: "10.00",
    rate: "$0.00",
    status: "active",
    weeklySchedule: [
      { day: "Monday", timeIn: "-:-", timeOut: "-:-" },
      { day: "TuesDay", timeIn: "-:-", timeOut: "-:-" },
      { day: "Wednesday", timeIn: "08:00", timeOut: "18:00" },
      { day: "Thursday", timeIn: "08:00", timeOut: "18:00" },
      { day: "Friday", timeIn: "-:-", timeOut: "-:-" },
      { day: "Saturday", timeIn: "-:-", timeOut: "-:-" },
    ],
    client: {
      id_: "1754576273740",
      id: "001",
      photo:
        "https://images.unsplash.com/photo-1593990965215-075c1f918806?q=80&w=987&auto=format&fit=crop",
      clientId: "CLI194827",
      firstName: "Balogun",
      lastName: "John",
      middleName: "James",
      gender: "Male",
      phone: "07000000011",
      email: "balogun.james@example.com",
      status: "active",
      dob: "07 Aug 1995",
      SocialSecurity: "348840f9",
      location: {
        address: "blv 205, califonia",
        city: "ParkView",
        state: "CA",
        zip: "29487",
      },
      phones: [
        { type: "Login", phoneNumber: "380672622574" },
        { type: "Home", phoneNumber: "380672622574" },
      ],
      medicalInfo: {
        admitted: "2025-09-04",
        livingWith: "202",
        ableToRespond: "---",
        allergies: "---",
        classification: "---",
        condition: "---",
        priority: "Yes",
      },
    },
    carePlan: {
      diagnosis: "",
      allergies: "",
      mobilityLevel: "",
      cognitiveLevel: "",
      communicationNeeds: "",
      emergencyContacts: "",
      specialRequests: "",
      fallRisk: "low",
      homeHazards: "",
    },
    visits: [
      {
        date: "",
        in: "",
        out: "",
        verifiedIn: "",
        verifiedOut: "",
      },
    ],
  },
];
