export const initialData = {
  profile_picture: "",
  previewPhoto: "",
  first_name: "",
  last_name: "",
  middle_name: "",
  gender: "",
  birth_date: "",
  status: "",
  social_security: "",
  email: "",
  password: "",
  password_confirmation: "",
  login_phone: "",
  address: "",
  city: "",
  state: "",
  zip: "",
  hire_date: "",
  application_date: "",
  orientation_date: "",
  signed_job_description_date: "",
  signed_policy_procedure_date: "",
  evaluated_assigned_date: "",
  last_evaluation_date: "",
  termination_date: "",
  number_of_references: 0,
};
